const boot=document.getElementById("boot");
const enter=document.getElementById("enter");
enter.onclick=()=>{boot.classList.add("hide");
setTimeout(()=>boot.remove(),650)};
setTimeout(()=>{if(boot)boot.classList.add("hide")},3200);
const theme=document.getElementById("theme");
theme.onclick=()=>document.body.classList.toggle("light");
const menu=document.getElementById("menu");
const nav=document.querySelector("nav");
menu.onclick=()=>{nav.style.display=nav.style.display==="flex"?"none":"flex";
                  nav.style.position="absolute";
                  nav.style.top="72px";
                  nav.style.left="0";
                  nav.style.right="0";nav.style.padding="20px";
                  nav.style.background="var(--bg)";
                  nav.style.flexDirection="column";
                  nav.style.borderBottom="1px solid var(--line)"};
document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>{if(innerWidth<851)nav.style.display="none"});
